# Site settings
title: Large Geometric Structures and Big Data @ AScI
#email: louis.theran@aalto.fi
# description: > # this means to ignore newlines until "baseurl:"
baseurl: "/lsbdseminar/" # the subpath of your site, e.g. /blog/
url: "https://aaltoscienceinst.github.io" # the base hostname & protocol for your site
#baseurl: "/lsbdseminar/" # the subpath of your site, e.g. /blog/
#url: "http://large-structures.asci.aalto.fi" # the base hostname & protocol for your site

# current seminar term
seminar_current_term: spring2017

# collections
collections:
    seminartalks:
        output: true

# Build settings
markdown: kramdown
future: true
