# Site settings
title: Challenges in Large Geometric Structures and Big Data
#email: louis.theran@aalto.fi
# description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://aaltoscienceinst.github.io/" # the base hostname & protocol for your site

# current seminar term
seminar_current_term: spring2016

# collections
collections:
    seminartalks:
        output: true

# Build settings
markdown: kramdown
future: true