# Site settings
title: Louis Theran
email: louis.theran@aalto.fi
# description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://theran.github.io" # the base hostname & protocol for your site
github_username:  theran
twitter_username: louistheran

# exclude from generating co-authors
my_authortag: louis

# collections
collections:
    papers:
        output: true

# Build settings
markdown: kramdown
